# Generated by Django 4.0.3 on 2022-04-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_registration',
            name='obj_Antifire_Machine_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.antifire_machine_type'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Antifire_People_Attended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.antifire_people_attended'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Causing_To_Death_Condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.causing_to_death_condition'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Dead_Degree_Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.dead_degree_level'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Dead_Family_Condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.dead_family_condition'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Dead_Gender_Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.dead_gender_person'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Dead_Social_Condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.dead_social_condition'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Death_Reason_In_Fire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.death_reason_in_fire'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Death_Time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.death_time'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Event_Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_event_location'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Event_Location_Place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_event_location_place'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Extinguisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_extinguisher'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Floor_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_floor_number'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Guilty_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_guilty_category'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Investigation_Result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_investigation_result'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Pistols',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_pistols'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Resistance_Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_resistance_level'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Source_Element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_source_element'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Widespread_Condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_widespread_condition'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Guilty_Person_Condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.guilty_person_condition'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Guilty_Person_Relation_To_Object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.guilty_person_relation_to_object'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Head_Of_Antifire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.head_of_antifire'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Injured_Person_Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.injured_person_gender'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Machines_Used_Antifire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.machines_used_antifire'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_OOG_Departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.oog_departure'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Primary_Antifire_Source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.primary_antifire_source'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Primary_Source_Usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.primary_source_usage'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Result_Of_Antifire_Machine_Work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.result_of_antifire_machine_work'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Transport_Condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.object_transport_condition'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Water_Source_Usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.water_source_usage'),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Water_Supply_Source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.water_supply_source'),
        ),
    ]
