# Generated by Django 4.0.3 on 2022-04-18 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eguide', '0003_object_registration_obj_guilty_person_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fire_Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_Reason_Code', models.IntegerField(default=0)),
                ('fire_Reason_Name', models.CharField(db_column='Наименование причины', max_length=250)),
            ],
            options={
                'verbose_name': 'Причина пожара',
                'verbose_name_plural': 'Причина пожара',
            },
        ),
        migrations.AlterModelOptions(
            name='antifire_machine_type',
            options={'verbose_name': 'Вид установки пожарной автоматики', 'verbose_name_plural': 'Вид установки пожарной автоматики'},
        ),
        migrations.AlterModelOptions(
            name='antifire_people_attended',
            options={'verbose_name': 'Участники тушения пожара', 'verbose_name_plural': 'Участники тушения пожара'},
        ),
        migrations.AlterModelOptions(
            name='building_antifire_service',
            options={'verbose_name': 'Вид пожарной охраны населенного пункта', 'verbose_name_plural': 'Вид пожарной охраны населенного пункта'},
        ),
        migrations.AlterModelOptions(
            name='building_type',
            options={'verbose_name': 'Вид населенного пункта', 'verbose_name_plural': 'Вид населенного пункта'},
        ),
        migrations.AlterModelOptions(
            name='causing_to_death_condition',
            options={'verbose_name': 'Условие способствующие гибели и трамвиованию людей', 'verbose_name_plural': 'Условие способствующие гибели и трамвиованию людей'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города и районы', 'verbose_name_plural': 'Города и районы'},
        ),
        migrations.AlterModelOptions(
            name='commercial_organisation',
            options={'verbose_name': 'Организационно-правовая форма организации', 'verbose_name_plural': 'Организационно-правовая форма организации'},
        ),
        migrations.AlterModelOptions(
            name='dead_degree_level',
            options={'verbose_name': 'Образование лица погибшего при пожаре', 'verbose_name_plural': 'Образование лица погибшего при пожаре'},
        ),
        migrations.AlterModelOptions(
            name='dead_family_condition',
            options={'verbose_name': 'Семейное положение погибшего при пожаре лица', 'verbose_name_plural': 'Семейное положение погибшего при пожаре лица'},
        ),
        migrations.AlterModelOptions(
            name='dead_gender_person',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='dead_social_condition',
            options={'verbose_name': 'Социальное положение погибшего при пожаре лица', 'verbose_name_plural': 'Социальное положение погибшего при пожаре лица'},
        ),
        migrations.AlterModelOptions(
            name='death_reason_in_fire',
            options={'verbose_name': 'Причина гибели людей при пожаре', 'verbose_name_plural': 'Причина гибели людей при пожаре'},
        ),
        migrations.AlterModelOptions(
            name='death_time',
            options={'verbose_name': 'Момент наступление смерти', 'verbose_name_plural': 'Момент наступление смерти'},
        ),
        migrations.AlterModelOptions(
            name='dist_organisation',
            options={'verbose_name': 'Орган ГПН ГСПБ', 'verbose_name_plural': 'Орган ГПН ГСПБ'},
        ),
        migrations.AlterModelOptions(
            name='fire_event_location',
            options={'verbose_name': 'Место возникновение пожара', 'verbose_name_plural': 'Место возникновение пожара'},
        ),
        migrations.AlterModelOptions(
            name='fire_event_location_place',
            options={'verbose_name': 'Место возникновение пожара-поле', 'verbose_name_plural': 'Место возникновение пожара-поле'},
        ),
        migrations.AlterModelOptions(
            name='fire_extinguisher',
            options={'verbose_name': 'Огнетушительные средства', 'verbose_name_plural': 'Огнетушительные средства'},
        ),
        migrations.AlterModelOptions(
            name='fire_floor_number',
            options={'verbose_name': 'Этаж на котором возник пожар', 'verbose_name_plural': 'Этаж на котором возник пожар'},
        ),
        migrations.AlterModelOptions(
            name='fire_guilty_category',
            options={'verbose_name': 'Категория виновника пожара', 'verbose_name_plural': 'Категория виновника пожара'},
        ),
        migrations.AlterModelOptions(
            name='fire_investigation_result',
            options={'verbose_name': 'Резулътат дознание по пожару', 'verbose_name_plural': 'Резулътат дознание по пожару'},
        ),
        migrations.AlterModelOptions(
            name='fire_objects',
            options={'verbose_name': 'Объект пожара', 'verbose_name_plural': 'Объект пожара'},
        ),
        migrations.AlterModelOptions(
            name='fire_pistols',
            options={'verbose_name': 'Пожарные стволы', 'verbose_name_plural': 'Пожарные стволы'},
        ),
        migrations.AlterModelOptions(
            name='fire_resistance_level',
            options={'verbose_name': 'Степен огнестойкости', 'verbose_name_plural': 'Степен огнестойкости'},
        ),
        migrations.AlterModelOptions(
            name='fire_widespread_condition',
            options={'verbose_name': 'Условие способствовавшие развитию пожара', 'verbose_name_plural': 'Условие способствовавшие развитию пожара'},
        ),
        migrations.AlterModelOptions(
            name='guilty_person_condition',
            options={'verbose_name': 'Состояние виновного лица', 'verbose_name_plural': 'Состояние виновного лица'},
        ),
        migrations.AlterModelOptions(
            name='guilty_person_relation_to_object',
            options={'verbose_name': 'Отношение виновного лица к объекту пожара', 'verbose_name_plural': 'Отношение виновного лица к объекту пожара'},
        ),
        migrations.AlterModelOptions(
            name='head_of_antifire',
            options={'verbose_name': 'Руководителб тушение пожара', 'verbose_name_plural': 'Руководителб тушение пожара'},
        ),
        migrations.AlterModelOptions(
            name='injured_person_gender',
            options={'verbose_name': 'Пол трамвированного лица', 'verbose_name_plural': 'Пол трамвированного лица'},
        ),
        migrations.AlterModelOptions(
            name='machines_used_antifire',
            options={'verbose_name': 'Техника исползованная при тушении пожара', 'verbose_name_plural': 'Техника исползованная при тушении пожара'},
        ),
        migrations.AlterModelOptions(
            name='ministery',
            options={'verbose_name': 'Ведомственная принадлежность организации', 'verbose_name_plural': 'Ведомственная принадлежность организации'},
        ),
        migrations.AlterModelOptions(
            name='object_securit_type',
            options={'verbose_name': 'Вид охраны объекта', 'verbose_name_plural': 'Вид охраны объекта'},
        ),
        migrations.AlterModelOptions(
            name='object_transport_condition',
            options={'verbose_name': 'Состояние транспорта и новостройки', 'verbose_name_plural': 'Состояние транспорта и новостройки'},
        ),
        migrations.AlterModelOptions(
            name='oog_departure',
            options={'verbose_name': 'Руководителб тушение пожара', 'verbose_name_plural': 'Выезд следственно-оперативной группы'},
        ),
        migrations.AlterModelOptions(
            name='organisation_name',
            options={'verbose_name': 'Тип предприятия,организации,учреждения', 'verbose_name_plural': 'Тип предприятия,организации,учреждения'},
        ),
        migrations.AlterModelOptions(
            name='primary_antifire_source',
            options={'verbose_name': 'Первичные средств пожаротушения', 'verbose_name_plural': 'Первичные средств пожаротушения'},
        ),
        migrations.AlterModelOptions(
            name='primary_source_usage',
            options={'verbose_name': 'Использование первичные средств', 'verbose_name_plural': 'Использование первичные средств'},
        ),
        migrations.AlterModelOptions(
            name='property_type',
            options={'verbose_name': 'Форма собственности обеъкта пожара', 'verbose_name_plural': 'Форма собственности объекта пожара'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Области', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='result_of_antifire_machine_work',
            options={'verbose_name': 'Результаты работы установок пожарной автоматики', 'verbose_name_plural': 'Результаты работы установок пожарной автоматики'},
        ),
        migrations.AlterModelOptions(
            name='water_source_usage',
            options={'verbose_name': 'Использование водоисточника', 'verbose_name_plural': 'Использование водоисточника'},
        ),
        migrations.AlterModelOptions(
            name='water_supply_source',
            options={'verbose_name': 'Водаснабжение на пожаре', 'verbose_name_plural': 'Водаснабжение на пожаре'},
        ),
        migrations.AlterField(
            model_name='antifire_machine_type',
            name='antifire_Machine_Type',
            field=models.CharField(db_column='Вид установки пожарной автоматики', max_length=250),
        ),
        migrations.AlterField(
            model_name='antifire_people_attended',
            name='attended_People',
            field=models.CharField(db_column='Участники тушения пожара', max_length=250),
        ),
        migrations.AlterField(
            model_name='building_type',
            name='bld_Type',
            field=models.CharField(db_column='Вид населенного пункта', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='causing_to_death_condition',
            name='death_Condition_Cause',
            field=models.CharField(db_column='Условие способствующие гибели', max_length=250),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_Name',
            field=models.CharField(db_column='Наименование города(райони)', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='commercial_organisation',
            name='corg_Name',
            field=models.CharField(db_column='Наименование', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='dead_degree_level',
            name='degree_Type',
            field=models.CharField(db_column='Образование', max_length=50),
        ),
        migrations.AlterField(
            model_name='dead_family_condition',
            name='family_Condition',
            field=models.CharField(db_column='Семейное положение', max_length=250),
        ),
        migrations.AlterField(
            model_name='dead_gender_person',
            name='gender_Type',
            field=models.CharField(db_column='Пол', max_length=50),
        ),
        migrations.AlterField(
            model_name='dead_social_condition',
            name='social_Condition',
            field=models.CharField(db_column='Социальное положение', max_length=100),
        ),
        migrations.AlterField(
            model_name='death_reason_in_fire',
            name='people_Death_Reason',
            field=models.CharField(db_column='Причина гибели людей', max_length=250),
        ),
        migrations.AlterField(
            model_name='death_time',
            name='death_Moment_Time',
            field=models.DateTimeField(db_column='Момент наступление смерти', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fire_event_location',
            name='fire_Event_Location_Name',
            field=models.CharField(db_column='Наименование', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_event_location_place',
            name='construction_Element',
            field=models.CharField(db_column='Коструктивные элементы', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_extinguisher',
            name='extinguisher_Type',
            field=models.CharField(db_column='Огнетушительные вещества', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_floor_number',
            name='floor_Type',
            field=models.CharField(db_column='Этаж', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_guilty_category',
            name='guilty_Person',
            field=models.CharField(db_column='Виновное лицо', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_investigation_result',
            name='adminisitrative_Responsibility',
            field=models.CharField(db_column='Админ, Ответственность', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_investigation_result',
            name='alleged_By',
            field=models.CharField(db_column='Кем возбуждено УД', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_investigation_result',
            name='criminal_Article_Of_RUz',
            field=models.CharField(db_column='Статьи УК Руз', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_investigation_result',
            name='investigation_Result',
            field=models.CharField(db_column='Результаты дознания', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_pistols',
            name='pistol_type',
            field=models.CharField(db_column='Виж плжарного ствола', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_resistance_level',
            name='resistance_Level',
            field=models.CharField(db_column='Степен огнестойкости', max_length=3),
        ),
        migrations.AlterField(
            model_name='fire_source_element',
            name='source_Element_Name',
            field=models.CharField(db_column='Наименование', max_length=250),
        ),
        migrations.AlterField(
            model_name='fire_widespread_condition',
            name='condition_Source',
            field=models.CharField(db_column='Условие способствовавшие развитию пожара', max_length=250),
        ),
        migrations.AlterField(
            model_name='guilty_person_condition',
            name='guilty_Person_Condition_Code',
            field=models.IntegerField(db_column='Состояние', default=0),
        ),
        migrations.AlterField(
            model_name='head_of_antifire',
            name='head_Name',
            field=models.CharField(db_column='Руководителб тушение пожара', max_length=250),
        ),
        migrations.AlterField(
            model_name='injured_person_gender',
            name='injured_Gender',
            field=models.CharField(db_column='Пол', max_length=10),
        ),
        migrations.AlterField(
            model_name='machines_used_antifire',
            name='machine_Type',
            field=models.CharField(db_column='Вид пожарной техники', max_length=250),
        ),
        migrations.AlterField(
            model_name='ministery',
            name='ministery_Name',
            field=models.CharField(db_column='Наименование', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='object_securit_type',
            name='object_Security_Name',
            field=models.CharField(db_column='Наименование', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='object_transport_condition',
            name='object_Transport_Condition_Type',
            field=models.CharField(db_column='Транспорт', max_length=250),
        ),
        migrations.AlterField(
            model_name='oog_departure',
            name='OOG_Departure_Group',
            field=models.CharField(db_column='Выезд СОГ', max_length=250),
        ),
        migrations.AlterField(
            model_name='primary_antifire_source',
            name='primary_Antifire_Source_Type',
            field=models.CharField(db_column='Первичные средств пожаротушения', max_length=250),
        ),
        migrations.AlterField(
            model_name='primary_source_usage',
            name='source_Usage_Type',
            field=models.CharField(db_column='Использование первичные средств', max_length=250),
        ),
        migrations.AlterField(
            model_name='property_type',
            name='property_Type',
            field=models.CharField(db_column='Форма собственности', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_Name',
            field=models.CharField(db_column='Наименование области', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='result_of_antifire_machine_work',
            name='result_Antifire_Machine_Work',
            field=models.CharField(db_column='Результаты работы', max_length=250),
        ),
        migrations.AlterField(
            model_name='water_source_usage',
            name='water_Usage_Purpose',
            field=models.CharField(db_column='Использование водоисточника', max_length=250),
        ),
        migrations.AlterField(
            model_name='water_supply_source',
            name='water_Supply_Type',
            field=models.CharField(db_column='Вид источника', max_length=250),
        ),
        migrations.AddField(
            model_name='object_registration',
            name='obj_Fire_Reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eguide.fire_reason'),
        ),
    ]
