from django.contrib import admin
from django.contrib.auth.models import Group,User
from .models import *

# Register your models here.
admin.site.site_header = 'Yong\'in havfsizlik hizmati'
admin.site.register(object_Registration)
admin.site.register(Region)
admin.site.register(City)
admin.site.register(dist_Organisation)
admin.site.register(building_Type)
admin.site.register(building_Antifire_Service)
admin.site.register(property_Type)
admin.site.register(commercial_Organisation)
admin.site.register(ministery)
admin.site.register(organisation_name)
admin.site.register(fire_Objects)
admin.site.register(object_Securit_Type)
admin.site.register(object_Transport_Condition)
admin.site.register(fire_Event_Location)
admin.site.register(fire_Event_Location_Place)
admin.site.register(fire_Source_Element)
admin.site.register(fire_guilty_category)
admin.site.register(guilty_Person_Relation_To_Object)
admin.site.register(guilty_Person_Condition)
admin.site.register(fire_Investigation_Result)
admin.site.register(fire_Floor_Number)
admin.site.register(fire_Resistance_Level)
admin.site.register(antifire_People_Attended)
admin.site.register(machines_Used_Antifire)
admin.site.register(fire_Pistols)
admin.site.register(fire_Extinguisher)
admin.site.register(primary_Antifire_Source)
admin.site.register(primary_Source_Usage)
admin.site.register(water_Supply_Source)
admin.site.register(water_Source_Usage)
admin.site.register(antifire_Machine_Type)
admin.site.register(result_Of_Antifire_Machine_Work)
admin.site.register(head_Of_Antifire)
admin.site.register(OOG_Departure)
admin.site.register(dead_Gender_Person)
admin.site.register(dead_Social_Condition)
admin.site.register(dead_Family_Condition)
admin.site.register(dead_Degree_Level)
admin.site.register(death_Reason_In_Fire)
admin.site.register(causing_To_Death_Condition)
admin.site.register(death_Time)
admin.site.register(injured_Person_Gender)

